### ISSUE TITLE
b-form-group always add mb-3 to class

### ISSUE THREAD

**Issue by makroxyz** [bootstrap-vue/bootstrap-vue-next#370]
as in the subject

```html
<b-form-group class="mb-0">....</b-form-group>
```

results in class="mb-3 mb-0" in html

**Comment by messenjer** [comment]
Yes, it's added here: https://github.com/cdmoro/bootstrap-vue-3/blob/aead8f0453b1a9248491dab27644a2b028946566/src/components/BFormGroup/BFormGroup.vue#L382 

I think we can remove it?

@cdmoro, @jclijmans What do you think?

**Comment by esl51** [comment]
`mb-3` is a utility class. I also think it should be removed.

**Comment by VividLemon** [comment]
> `mb-3` is a utility class. I also think it should be removed.

I added a todo note in my repo. When I get around to testing and converting that component, I will likely remove it.(The problem is not that it's a utility, but that there would be no way currently to add classes onto that component, if one did want to keep the margin, they could not)

**Comment by esl51** [comment]
Maybe removal is not the answer. It would be great to implement some sort of global component configurator like in [BootstrapVue](https://bootstrap-vue.org/docs/reference/settings#setting-config-via-individual-component-group-plugin-imports). But since the original bootstrap doesn't have such a component, it generally doesn't fit. I think the choice is yours. If the concept is "only original components", then removing it fits in like never before.

**Comment by VividLemon** [comment]
I'll eventually remove it
