### ISSUE TITLE
BDropdown boundary not working

### ISSUE THREAD

**Issue by esl51** [bootstrap-vue/bootstrap-vue-next#800]
**Describe the bug**
Can't change the `boundary` prop of BDropdown.

**To Reproduce**
```vue
<template>
  <div
    class="test"
    style="overflow-x: auto; width: 200px; height: 50px"
  >
    <b-dropdown
      variant="danger"
      no-caret
      boundary="viewport"
    >
      <template #button-content> ... </template>
      <b-dropdown-item-button>Action 1</b-dropdown-item-button>
      <b-dropdown-item-button>Action 2</b-dropdown-item-button>
    </b-dropdown>
  </div>
</template>
<script setup lang="ts">
import { ref } from 'vue'
const card = ref(null)
</script>
```

**Expected behavior**
`.dropdown-menu` appears outside the `.test`.

**Screenshots**
![image](https://user-images.githubusercontent.com/3800914/201120921-da6c6a2b-7a4d-4c5c-b327-6ff6ce49d826.png)
![image](https://user-images.githubusercontent.com/3800914/201123897-98dfb06d-2ecf-40d8-b7fb-8230e7e98670.png)

**Environment:**
 - OS: MacOS Monterey 12.6.1
 - Version: 0.4.7

**Comment by esl51** [comment]
`:popper-opts="{ strategy: 'fixed' }"` instead of `boundary="viewport"` [solved the problem](https://stackoverflow.com/questions/70098157/bootstrap-5-1-3-dropdown-data-bs-boundary-no-longer-works), but it's not quite clear why `boundary` then.

**Comment by VividLemon** [comment]
I'd suspect because it's not fully finished. I'd like for the floating elements to get replaced with a Vue specific alternative, such as https://github.com/Akryum/floating-vue . Popper is "fine", but I could move everything into Vue, it would make it easier to use. But I have to do some research on that one, it seems like I could use the hovering pieces, while preserving also using the bootstrap css. 

But that's like 3 big steps away on my list of things to do.

**Comment by VividLemon** [comment]
0.8.0 is a rewrite of BDropdown. I suspect this specific issue with Boundary is fixed. Regardless, in 0.8.0, the prop is removed. I have created a new issue to track adding it back in, so that overflow can be detected. But as of right now, it is not a feature.
